name: LobbySystem
main: org.bysenom.lobby.LobbySystem
version: ${version}
author: bySenom
description: "Zentraler Lobby- und Matchmaking-Hub für MinecraftSurvivors."
api-version: 1.21
softdepend: [MinecraftSurvivors]
commands:
  lobby:
    description: "Öffnet das Lobby-Menü"
    usage: "/lobby"
  queue:
    description: "Queue: /queue join|leave|status|next"
    usage: "/queue <join|leave|status|next>"
  startsurvivors:
    description: "Admin: Startet eine Survivors-Runde für gequeue-te Spieler"
    usage: "/startsurvivors"
  lobbyreload:
    description: "Reloadet die Lobby-Konfiguration (BossBar/AutoStart)"
    usage: "/lobbyreload"
    permission: lobby.admin
permissions:
  lobby.admin:
    description: "Adminrechte für LobbySystem"
    default: op
