# language: yaml
name: MinecraftSurvivors
version: '${version}'
main: org.bysenom.minecraftSurvivors.MinecraftSurvivors
api-version: '1.21'
description: "Vampire Survivors like Minigame"
authors:
  - bySenom
commands:
  msmenu:
    description: "Öffnet das MinecraftSurvivors Menü (Admin)."
    usage: "/msmenu"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  msstart:
    description: "Startet das Spiel (Admin/Op)."
    usage: "/msstart"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  msconfig:
    description: "Verwaltet MinecraftSurvivors Konfiguration (reload)."
    usage: "/msconfig reload"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  msstats:
    description: "DPS/HPS Anzeige: /msstats mode <actionbar|bossbar|scoreboard|off> | toggle | top [dps|hps] [n] | show"
    usage: "/msstats <sub>"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  msversion:
    description: "Zeigt Plugin-Version an."
    usage: "/msversion"

  mshealth:
    description: "Zeigt eine kompakte Statusübersicht (Admin)."
    usage: "/mshealth"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  spawnglyph:
    description: "(DEV) Spawnt eine Glyphen-Sockel in deiner Nähe: /spawnglyph <abilityKey|random>"
    usage: "/spawnglyph <abilityKey|random>"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."

  party:
    description: "Party-System: /party create|invite|join|leave|disband|list"
    usage: "/party <sub>"

  msversion:
    description: "Zeigt Plugin-Version an."
    usage: "/msversion"

  mshealth:
    description: "Zeigt eine kompakte Statusübersicht (Admin)."
    usage: "/mshealth"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
permissions:
  minecraftsurvivors.admin:
    description: "Erlaubnis zum Starten/Stoppen und Admin-Kommandos"
    default: op
