# language: yaml
name: MinecraftSurvivors
version: '${version}'
main: org.bysenom.minecraftSurvivors.MinecraftSurvivors
api-version: '1.21'
description: "Vampire Survivors like Minigame"
authors:
  - bySenom
commands:
  msmenu:
    description: "Öffnet das Hauptmenü / Admin GUI. Subcommands: (keine)"
    usage: |-
      /msmenu
  msstart:
    description: "Startet direkt eine Survivors-Runde (Admin/Op)."
    usage: |-
      /msstart
  msconfig:
    description: |-
      MinecraftSurvivors Konfiguration verwalten.
      Subcommands:
        reload                      - Lädt config neu von Disk
        preset <name>               - Aktiviert Preset
        preset list                 - Listet verfügbare Presets
        preset show <name>          - Zeigt Werte eines Presets
        set <path> <value>          - Setzt einen Wert (wartet auf confirm)
        confirm / cancel            - Bestätigt oder verwirft letzten set-Vorschlag
        show                        - Zeigt Root-Konfigurationspfade
    usage: |-
      /msconfig reload
      /msconfig preset <name>
      /msconfig preset list
      /msconfig preset show <name>
      /msconfig set <path> <value>
      /msconfig confirm
      /msconfig cancel
      /msconfig show
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  msstats:
    description: |-
      Statistiken & Darstellung (DPS/HPS). Subcommands:
        mode <actionbar|bossbar|scoreboard|off>  - Anzeige-Modus setzen
        toggle                                   - Ein/Aus schalten
        top <dps|hps> [n]                        - Top-Liste anzeigen (Standard n=5)
        show                                     - Eigene aktuellen Werte anzeigen
        reset                                    - Persönliche Messung zurücksetzen
    usage: |-
      /msstats mode <actionbar|bossbar|scoreboard|off>
      /msstats toggle
      /msstats top <dps|hps> [anzahl]
      /msstats show
      /msstats reset
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  msversion:
    description: "Zeigt Plugin-Version an."
    usage: "/msversion"
  mshealth:
    description: "Kurze Status-/Health-Übersicht (Admin)."
    usage: "/mshealth"
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  spawnglyph:
    description: |-
      Entwicklerbefehl zum Spawnen einer Glyphe.
      Subcommands / Parameter:
        <abilityKey>  - Spezifische Ability-Glyphe
        random        - Zufällige Glyphe
    usage: |-
      /spawnglyph <abilityKey>
      /spawnglyph random
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  party:
    description: |-
      Party-System. Subcommands:
        create                    - Neue Party erstellen (wenn du keine hast)
        invite <Spieler>          - Spieler einladen
        join <LeaderName>         - Party eines Leaders beitreten (nach Einladung)
        leave                     - Eigene Party verlassen
        disband                   - Eigene Party (falls Leader) auflösen
        list                      - Mitglieder der eigenen Party anzeigen
    usage: |-
      /party create
      /party invite <Spieler>
      /party join <Leader>
      /party leave
      /party disband
      /party list
  fx:
    description: "Test visueller Effekte (Meteor/Genkidama). Subcommands: testgenkidama, meteor <h> <speed> <radius> <damage>"
    usage: |-
      /fx testgenkidama
      /fx meteor <height> <speed> <radius> <damage>
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  msboss:
    description: |-
      Debug-Bosssteuerung (Admin): spawn|kill|barrage|meteor|shockwave|lightning
    usage: |-
      /msboss spawn
      /msboss kill
      /msboss barrage
      /msboss meteor
      /msboss shockwave
      /msboss lightning
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
  msroundstats:
    description: |-
      Zeigt Round-Statistics an und exportiert Reports.
      Subcommands:
        show [page]                - Öffnet GUI mit Round-Stats (page 1=Sources, 2=Players)
        export [json|csv|html]     - Exportiert letzten Round-Report
        openfile <filename>        - Zeigt Pfad der Report-Datei
    usage: |-
      /msroundstats show [page]
      /msroundstats export [json|csv|html]
      /msroundstats openfile <filename>
    permission: minecraftsurvivors.admin
    permission-message: "§cKeine Berechtigung."
permissions:
  minecraftsurvivors.admin:
    description: "Erlaubnis für Admin-/Management-Kommandos"
    default: op
